### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by PopeHax** [artemiswkearney/CustomMenuText#4]
Would it be possible to get this updated for 1.6.0.
had been able to just bring it across on previous updates but not this time. :(

**Comment by greavettey** [comment]
Maybe reopen this? It doesn't seem to work for me no matter what I do...

**Comment by PopeHax** [comment]
yeah it stopped working for me completely now i was getting it to go by playing or just starting a map and then it would kick in after that

**Comment by artemiswkearney** [comment]
Working in 1.6 (and 1.7) as of version 3.1.1
